/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import type { PluginTag } from "./types";

const TAGS_IT: Record<PluginTag, string> = {
    Accessibility: "Accessibilità",
    Activity: "Attività",
    Appearance: "Aspetto",
    Chat: "Chat",
    Commands: "Comandi",
    Console: "Console",
    Customisation: "Personalizzazione",
    Developers: "Sviluppatori",
    Emotes: "Emoji",
    Friends: "Amici",
    Fun: "Divertimento",
    Media: "Multimedia",
    Notifications: "Notifiche",
    Organisation: "Organizzazione",
    Privacy: "Privacy",
    Reactions: "Reazioni",
    Roles: "Ruoli",
    Servers: "Server",
    Shortcuts: "Scorciatoie",
    Utility: "Utilità",
    Voice: "Voce"
};

export function italianPluginTag(tag: PluginTag): string {
    return TAGS_IT[tag] ?? tag;
}

const EXACT_SETTING_NAMES: Record<string, string> = {
    activityType: "Tipo di attività",
    additionalQuotes: "Citazioni aggiuntive",
    additionalQuotesDelimiter: "Delimitatore citazioni aggiuntive",
    agreedToGuidelines: "Linee guida accettate",
    allowEveryone: "Consenti @everyone",
    allowMentions: "Consenti menzioni",
    anonymiseByDefault: "Anonimizza per impostazione predefinita",
    apiKey: "Chiave API",
    applyColorOnlyInDms: "Applica colore solo nei messaggi diretti",
    applyColorOnlyToUsersWithoutColor: "Applica colore solo agli utenti senza colore",
    applyToIgnoredUsers: "Applica anche agli utenti ignorati",
    autoDisable: "Disattiva automaticamente",
    autoTranslate: "Traduzione automatica",
    backgroundCheck: "Controllo in background",
    bgOpacity: "Opacità sfondo",
    blurAmount: "Intensità sfocatura",
    botNotifications: "Notifiche bot",
    callNotifications: "Notifiche chiamate",
    canCollapseDmSection: "Consenti compressione sezione messaggi diretti",
    channelPingColor: "Colore menzioni canale",
    channelToAffect: "Tipo di messaggi diretti",
    chatBarButton: "Pulsante nella barra chat",
    checkInterval: "Intervallo di controllo",
    closeAllFolders: "Chiudi tutte le cartelle",
    closeAllHomeButton: "Chiudi cartelle con Home",
    closeOthers: "Chiudi le altre cartelle",
    closeServerFolder: "Chiudi la cartella del server",
    collapseDeleted: "Comprimi messaggi eliminati",
    colorChatMessages: "Colora i messaggi della chat",
    colorMobileIndicator: "Colore indicatore mobile",
    consistent: "Nome file coerente",
    contentHint: "Indicazione contenuto",
    copyRoleColorInProfilePopout: "Copia colore ruolo dal profilo",
    copyUnicode: "Copia carattere Unicode",
    customEngineName: "Nome motore personalizzato",
    customEngineURL: "URL motore personalizzato",
    deafenMessage: "Messaggio audio disattivato",
    dearrowByDefault: "Dearrow automatico",
    deeplApiKey: "Chiave API DeepL",
    defaultAllowedUsersAndRolesDropdownState: "Apri utenti e ruoli consentiti per impostazione predefinita",
    defaultLayout: "Layout predefinito",
    defaultSortOrder: "Ordinamento predefinito",
    deleteStyle: "Stile messaggi eliminati",
    disableAnalytics: "Disabilita analisi",
    disableEmbedPermissionCheck: "Disabilita controllo permessi incorporamenti",
    disableFade: "Disabilita dissolvenza",
    disableLoggers: "Disabilita logger",
    disableSpotifyLogger: "Disabilita logger Spotify",
    displayNames: "Nomi visualizzati",
    displayStyle: "Stile di visualizzazione",
    dmNotifications: "Notifiche messaggi diretti",
    dmSectionCollapsed: "Sezione messaggi diretti compressa",
    echoCancellation: "Cancellazione dell'eco",
    emojiSize: "Dimensione emoji",
    enableButtons: "Abilita pulsanti",
    enableDeleteOnClick: "Abilita eliminazione con clic",
    enableDiscordPresetQuotes: "Abilita citazioni predefinite di Discord",
    enableDoubleClickToEdit: "Abilita doppio clic per modificare",
    enableDoubleClickToReply: "Abilita doppio clic per rispondere",
    enableEmojiBypass: "Abilita bypass emoji",
    enablePluginPresetQuotes: "Abilita citazioni del plugin",
    enableStickerBypass: "Abilita bypass adesivi",
    enableStreamQualityBypass: "Abilita qualità streaming Nitro",
    enableTimestamps: "Abilita timestamp",
    file: "File",
    forceOpen: "Forza apertura",
    frameRate: "Frequenza fotogrammi",
    friendNicknames: "Soprannomi amici",
    greetMode: "Modalità saluto",
    groupDmNotifications: "Notifiche messaggi diretti di gruppo",
    hideBlockedUsers: "Nascondi utenti bloccati",
    hideButton: "Nascondi pulsante",
    hideFriendRequestsCount: "Nascondi conteggio richieste amicizia",
    hideMessageRequestsCount: "Nascondi conteggio richieste messaggi",
    hidePremiumOffersCount: "Nascondi conteggio offerte Nitro",
    hideTimestamps: "Nascondi timestamp",
    hideUnreads: "Nascondi non letti",
    hideWithActivity: "Nascondi con altra attività",
    hideWithSpotify: "Nascondi con Spotify",
    hoverControls: "Controlli al passaggio del mouse",
    hyperLinkText: "Testo collegamento",
    iconSize: "Dimensione icona",
    iconSpacing: "Spaziatura icone",
    idList: "Elenco ID",
    idleTimeout: "Tempo prima dello stato inattivo",
    ignoreBlockedAndIgnored: "Ignora utenti bloccati e ignorati",
    ignoreBots: "Ignora bot",
    ignoreChannels: "Canali da ignorare",
    ignoreCompeting: "Ignora attività di competizione",
    ignoreGuilds: "Server da ignorare",
    ignoreListening: "Ignora attività di ascolto",
    ignorePlaying: "Ignora attività di gioco",
    ignoreSelf: "Ignora i tuoi messaggi",
    ignoreStreaming: "Ignora attività di streaming",
    ignoreUsers: "Utenti da ignorare",
    ignoreWatching: "Ignora attività di visione",
    image: "Immagine",
    imgSize: "Dimensione immagine",
    inReplies: "Nelle risposte",
    includeBlockedUsers: "Includi utenti bloccati",
    includeCurrentChannel: "Includi canale corrente",
    includeIgnoredUsers: "Includi utenti ignorati",
    includeMutedChannels: "Includi canali silenziati",
    includeVencordInfoWhenCopying: "Includi informazioni Vencord durante la copia",
    indicatorMode: "Modalità indicatore",
    inlineEdits: "Modifiche in linea",
    invertScroll: "Inverti scorrimento",
    joinMessage: "Messaggio di entrata",
    kagiSession: "Token sessione Kagi",
    keepIcons: "Mantieni icone",
    keepSpotifyActivityOnIdle: "Mantieni attività Spotify durante inattività",
    largeImageLink: "Link immagine grande",
    largeImageType: "Tipo immagine grande",
    largeTextString: "Testo immagine grande",
    latinOnly: "Solo caratteri latini",
    leaveMessage: "Messaggio di uscita",
    lengthBasedTimeout: "Durata in base alla lunghezza del messaggio",
    lightness: "Luminosità",
    listMode: "Modalità elenco",
    logDeletedAttachments: "Registra allegati eliminati",
    logDeletes: "Registra messaggi eliminati",
    logEdits: "Registra messaggi modificati",
    loop: "Ripeti in loop",
    memberList: "Elenco membri",
    memberListColors: "Colori elenco membri",
    messageBackgroundColor: "Colore sfondo messaggi",
    messageContextMenu: "Menu contestuale messaggi",
    messagePopoverButton: "Pulsante popup messaggi",
    messageSaturation: "Saturazione messaggi",
    method: "Metodo",
    missingArt: "Copertina mancante",
    moveMessage: "Messaggio di spostamento",
    multiplier: "Moltiplicatore",
    muteMessage: "Messaggio microfono disattivato",
    nameFormat: "Formato nome",
    nearestNeighbour: "Interpolazione Nearest Neighbour",
    nitroFirst: "Priorità Nitro",
    noSpotifyAutoPause: "Disabilita pausa automatica Spotify",
    noiseSuppression: "Soppressione del rumore",
    notificationVolume: "Volume notifiche",
    notifyOnAutoConnect: "Notifica connessione automatica",
    notifyReviews: "Notifica nuove recensioni",
    offlineRemovals: "Rimozioni durante offline",
    oldIcon: "Icone precedenti",
    onlySnow: "Solo Snow Halation",
    opacity: "Opacità",
    organizeMenu: "Organizza menu",
    originalImagesInChat: "Immagini originali in chat",
    permissionsSortOrder: "Ordinamento permessi",
    persistState: "Mantieni stato",
    pinOrder: "Ordine elementi fissati",
    pingColor: "Colore menzioni",
    preferUDP: "Preferisci UDP",
    previousButtonRestartsTrack: "Il pulsante precedente riavvia il brano",
    prioritizeServerProfile: "Dai priorità al profilo server",
    pronounsFormat: "Formato pronomi",
    randomisedLength: "Lunghezza caratteri casuali",
    rate: "Velocità",
    reactionCount: "Numero di reazioni",
    receivedInput: "Lingua messaggi ricevuti",
    receivedOutput: "Traduci messaggi ricevuti in",
    refreshInterval: "Intervallo di aggiornamento",
    remainInIdle: "Rimani inattivo al ritorno",
    replaceElements: "Elementi da sostituire",
    replaceMessageContents: "Sostituisci timestamp nei messaggi",
    replacementEngine: "Motore di ricerca sostitutivo",
    requireModifier: "Richiedi tasto modificatore",
    resolution: "Risoluzione",
    roleIconFileFormat: "Formato icona ruolo",
    saveZoomValues: "Salva valori di zoom",
    sayOwnName: "Pronuncia il proprio nome",
    scrobblerBackend: "Servizio di scrobbling",
    sentInput: "Lingua dei tuoi messaggi",
    sentOutput: "Traduci i tuoi messaggi in",
    showAutoTranslateTooltip: "Mostra suggerimento traduzione automatica",
    showChatBarButton: "Mostra pulsante nella barra chat",
    showConnections: "Mostra account collegati",
    showInMemberList: "Mostra nell'elenco membri",
    showInMessages: "Mostra nei messaggi",
    showInUserProfileModal: "Mostra nel profilo utente",
    showVoiceChannelSectionHeader: "Mostra intestazione canale vocale",
    square: "Lente quadrata",
    stickerSize: "Dimensione adesivi",
    stickToMarkers: "Aggancia ai marcatori",
    transformCompoundSentence: "Trasforma frasi composte",
    transformEmojis: "Trasforma emoji simulate",
    transformStickers: "Trasforma adesivi simulati",
    unmuteMessage: "Messaggio microfono riattivato",
    undeafenMessage: "Messaggio audio riattivato",
    useHyperLinks: "Usa collegamenti ipertestuali",
    useNative: "Stile notifiche",
    userPingColor: "Colore menzioni utente",
    volume: "Volume",
    zoom: "Zoom",
    zoomSpeed: "Velocità zoom"
};

const WORDS: Record<string, string> = {
    add: "Aggiungi", allow: "Consenti", auto: "Automatico", background: "Sfondo", blocked: "Bloccati",
    button: "Pulsante", buttons: "Pulsanti", channel: "Canale", channels: "Canali", chat: "Chat",
    color: "Colore", colors: "Colori", custom: "Personalizzato", default: "Predefinito", disable: "Disabilita",
    display: "Visualizzazione", dm: "DM", dms: "DM", enable: "Abilita", friend: "Amico", friends: "Amici",
    guild: "Server", guilds: "Server", hide: "Nascondi", icon: "Icona", icons: "Icone", ignore: "Ignora",
    image: "Immagine", images: "Immagini", include: "Includi", link: "Link", links: "Link", list: "Elenco",
    message: "Messaggio", messages: "Messaggi", mode: "Modalità", name: "Nome", notification: "Notifica",
    notifications: "Notifiche", only: "Solo", plugin: "Plugin", profile: "Profilo", reaction: "Reazione",
    reactions: "Reazioni", role: "Ruolo", roles: "Ruoli", server: "Server", show: "Mostra", size: "Dimensione",
    status: "Stato", text: "Testo", theme: "Tema", themes: "Temi", user: "Utente", users: "Utenti",
    use: "Usa", voice: "Voce", volume: "Volume", zoom: "Zoom", settings: "Impostazioni", format: "Formato",
    style: "Stile", source: "Sorgente", current: "Corrente", activity: "Attività", activities: "Attività",
    sort: "Ordina", order: "Ordine", log: "Registra", deleted: "Eliminati", edited: "Modificati",
    timestamp: "Timestamp", timestamps: "Timestamp", folder: "Cartella", folders: "Cartelle", open: "Apri",
    close: "Chiudi", menu: "Menu", opacity: "Opacità", interval: "Intervallo", speed: "Velocità",
    quality: "Qualità", streaming: "Streaming", typing: "Digitazione", indicator: "Indicatore", avatar: "Avatar",
    avatars: "Avatar", sticker: "Adesivo", stickers: "Adesivi", emoji: "Emoji", emojis: "Emoji"
};

function splitIdentifier(id: string): string[] {
    return id
        .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
        .replace(/[_-]+/g, " ")
        .trim()
        .split(/\s+/)
        .filter(Boolean);
}

function translateWords(words: string[]): string {
    if (!words.length) return "";

    // Common noun suffixes read more naturally before their subject in Italian.
    const last = words.at(-1)?.toLowerCase();
    const nounSuffixes: Record<string, string> = {
        size: "Dimensione",
        color: "Colore",
        volume: "Volume",
        opacity: "Opacità",
        format: "Formato",
        mode: "Modalità",
        interval: "Intervallo",
        speed: "Velocità"
    };
    if (last && nounSuffixes[last] && words.length > 1) {
        const subject = words.slice(0, -1).map(w => WORDS[w.toLowerCase()] ?? w).join(" ").toLowerCase();
        return `${nounSuffixes[last]} ${subject}`;
    }

    return words.map((word, i) => {
        const translated = WORDS[word.toLowerCase()] ?? word;
        return i === 0 ? translated : translated.toLowerCase();
    }).join(" ");
}

export function italianSettingName(id: string): string {
    return EXACT_SETTING_NAMES[id] ?? translateWords(splitIdentifier(id));
}
