/*
 * Nomi italiani visualizzati dei plugin.
 * IMPORTANTE: non modifica mai gli ID interni dei plugin.
 */

const italianPluginNames: Record<string, string> = {
    AccountPanelServerProfile: "Profilo server nel pannello account",
    AddAttachments: "Aggiungi allegati",
    AlwaysAnimate: "Anima sempre",
    AlwaysExpandRoles: "Espandi sempre i ruoli",
    AlwaysTrust: "Considera sempre attendibile",
    AnonymiseFileNames: "Anonimizza nomi file",
    AppleMusicRichPresence: "Rich Presence Apple Music",
    AutomodContext: "Contesto AutoMod",
    AutoDNDWhilePlaying: "Non disturbare durante il gioco",

    BadgeAPI: "API badge",
    BANger: "BANger",
    BetterFolders: "Cartelle migliorate",
    BetterGifAltText: "Testo alternativo GIF migliorato",
    BetterGifPicker: "Selettore GIF migliorato",
    BetterNotesBox: "Riquadro note migliorato",
    BetterRoleContext: "Menu ruoli migliorato",
    BetterRoleDot: "Indicatore ruolo migliorato",
    BetterSessions: "Sessioni migliorate",
    BetterSettings: "Impostazioni migliorate",
    BetterUploadButton: "Pulsante caricamento migliorato",
    BiggerStreamPreview: "Anteprima streaming più grande",
    BlurNSFW: "Sfoca contenuti NSFW",

    CallTimer: "Timer chiamata",
    CharacterCounter: "Contatore caratteri",
    ChatInputButtonAPI: "API pulsanti barra chat",
    ClearURLs: "Pulisci URL",
    ClientTheme: "Tema client",
    ColorSighted: "Colori più visibili",
    CommandsAPI: "API comandi",
    ConcatenatedComponentExtractor: "Estrattore componenti concatenati",
    ConsoleJanitor: "Pulizia console",
    ConsoleShortcuts: "Scorciatoie console",
    ContextMenuAPI: "API menu contestuale",
    CopyEmojiMarkdown: "Copia Markdown emoji",
    CopyFileContents: "Copia contenuto file",
    CopyStickerLinks: "Copia link sticker",
    CopyUserURLs: "Copia URL utenti",
    CrashHandler: "Gestione crash",
    CtrlEnterSend: "Invia con Ctrl+Invio",
    CustomCommands: "Comandi personalizzati",
    CustomIdle: "Inattività personalizzata",
    CustomRPC: "Rich Presence personalizzata",

    Dearrow: "DeArrow",
    Decor: "Decorazioni",
    DisableCallIdle: "Disattiva inattività in chiamata",
    DontRoundMyTimestamps: "Non arrotondare i timestamp",
    DynamicImageModalAPI: "API modale immagini dinamiche",

    Experiments: "Esperimenti",
    ExpressionCloner: "Clona espressioni",

    F8Break: "Interruzione F8",
    FakeNitro: "Nitro simulato",
    FakeProfileThemes: "Temi profilo simulati",
    FavoriteEmojiFirst: "Emoji preferite prima",
    FavoriteGifSearch: "Ricerca GIF preferite",
    FixCodeblockGap: "Correggi spazio blocchi codice",
    FixImagesQuality: "Correggi qualità immagini",
    FixSpotifyEmbeds: "Correggi anteprime Spotify",
    FixYoutubeEmbeds: "Correggi anteprime YouTube",
    ForceOwnerCrown: "Forza corona proprietario",
    FriendInvites: "Inviti amici",
    FriendsSince: "Amici da",
    FullSearchContext: "Contesto completo ricerca",
    FullUserInChatbox: "Utente completo nella chat",

    GameActivityToggle: "Interruttore attività di gioco",
    GifPaste: "Incolla GIF",
    GreetStickerPicker: "Selettore sticker di saluto",

    HideMedia: "Nascondi contenuti multimediali",

    IgnoreActivities: "Ignora attività",
    ImageFilename: "Nome file immagine",
    ImageLink: "Link immagine",
    ImageZoom: "Zoom immagini",
    ImplicitRelationships: "Relazioni implicite",
    InvisibleChat: "Chat invisibile",
    IrcColors: "Colori IRC",

    KeepCurrentChannel: "Mantieni canale corrente",

    LoadingQuotes: "Frasi di caricamento",

    MaskedLinkPaste: "Incolla link mascherati",
    MemberCount: "Conteggio membri",
    MemberListDecoratorsAPI: "API decorazioni lista membri",
    MentionAvatars: "Avatar nelle menzioni",
    MessageAccessoriesAPI: "API accessori messaggi",
    MessageClickActions: "Azioni al clic sui messaggi",
    MessageDecorationsAPI: "API decorazioni messaggi",
    MessageEventsAPI: "API eventi messaggi",
    MessageLatency: "Latenza messaggi",
    MessageLinkEmbeds: "Anteprime link messaggi",
    MessageLogger: "Registro messaggi",
    MessagePopoverAPI: "API pulsanti messaggio",
    MessageUpdaterAPI: "API aggiornamento messaggi",
    MoreCommands: "Più comandi",
    MoreKaomoji: "Più kaomoji",
    MoreQuickReactions: "Più reazioni rapide",
    MoreUserTags: "Più etichette utente",
    Moyai: "Moyai",
    MusicRichPresence: "Rich Presence musicale",
    MutualGroupDMs: "Gruppi DM in comune",

    NewGuildSettings: "Impostazioni nuovi server",
    NoBlockedMessages: "Nascondi messaggi bloccati",
    NoDefaultHangStatus: "Nessuno stato Hang predefinito",
    NoDevtoolsWarning: "Nessun avviso DevTools",
    NoF1: "Disattiva F1",
    NoMaskedUrlPaste: "Disattiva incolla URL mascherati",
    NoMiddleClickPaste: "Disattiva incolla col clic centrale",
    NoMosaic: "Disattiva mosaico",
    NoOnboardingDelay: "Nessun ritardo onboarding",
    NoPendingCount: "Nascondi conteggio richieste",
    NoProfileThemes: "Disattiva temi profilo",
    NoReplyMention: "Nessuna menzione nelle risposte",
    NoRPC: "Disattiva Rich Presence",
    NoScreensharePreview: "Nascondi anteprima condivisione schermo",
    NoServerEmojis: "Disattiva emoji del server",
    NoSystemBadge: "Nascondi badge di sistema",
    NoTrack: "Disattiva tracciamento",
    NoTypingAnimation: "Disattiva animazione digitazione",
    NoUnblockToJump: "Vai al messaggio senza sbloccare",
    NormalizeMessageLinks: "Normalizza link messaggi",
    NotificationVolume: "Volume notifiche",
    NoticesAPI: "API avvisi",
    NSFWGateBypass: "Bypass controllo NSFW",

    OnePingPerDM: "Un ping per DM",
    oneko: "Oneko",
    OpenInApp: "Apri nell'app",
    OverrideForumDefaults: "Sovrascrivi impostazioni forum",

    PartyMode: "Modalità festa",
    PauseInvitesForever: "Pausa inviti permanente",
    PermissionFreeWill: "Permessi liberi",
    PermissionsViewer: "Visualizzatore permessi",
    petpet: "PetPet",
    PictureInPicture: "Picture-in-Picture",
    PinDMs: "Fissa DM",
    PlainFolderIcon: "Icona cartella semplice",
    PlatformIndicators: "Indicatori piattaforma",
    PreviewMessage: "Anteprima messaggio",

    QuickMention: "Menzione rapida",
    QuickReply: "Risposta rapida",

    ReactErrorDecoder: "Decodifica errori React",
    ReadAllNotificationsButton: "Leggi tutte le notifiche",
    RelationshipNotifier: "Notifiche relazioni",
    ReplaceGoogleSearch: "Sostituisci ricerca Google",
    ReplyTimestamp: "Timestamp nelle risposte",
    ResurrectHome: "Ripristina Home",
    RevealAllSpoilers: "Mostra tutti gli spoiler",
    ReverseImageSearch: "Ricerca inversa immagini",
    ReviewDB: "ReviewDB",
    RoleColorEverywhere: "Colore ruolo ovunque",

    SecretRingToneEnabler: "Abilita suoneria segreta",
    SendTimestamps: "Invia timestamp",
    ServerInfo: "Informazioni server",
    ServerListAPI: "API lista server",
    ServerListIndicators: "Indicatori lista server",
    Settings: "Impostazioni",
    SettingsStoreAPI: "API archivio impostazioni",
    ShikiCodeblocks: "Blocchi codice Shiki",
    ShowAllMessageButtons: "Mostra tutti i pulsanti messaggio",
    ShowConnections: "Mostra connessioni",
    ShowHiddenChannels: "Mostra canali nascosti",
    ShowHiddenThings: "Mostra elementi nascosti",
    ShowMeYourName: "Mostrami il tuo nome",
    ShowTimeoutDuration: "Mostra durata timeout",
    SilentMessageToggle: "Interruttore messaggi silenziosi",
    SilentTyping: "Digitazione silenziosa",
    SortFriendRequests: "Ordina richieste di amicizia",
    SpotifyControls: "Controlli Spotify",
    SpotifyCrack: "Miglioramenti Spotify",
    SpotifyShareCommands: "Comandi condivisione Spotify",
    StartupTimings: "Tempi di avvio",
    StickerPaste: "Incolla sticker",
    StreamerModeOnStream: "Modalità streamer durante lo streaming",
    Summaries: "Riepiloghi",
    SuperReactionTweaks: "Modifiche Super Reaction",
    SupportHelper: "Assistente supporto",

    TenorGifSearch: "Ricerca GIF Tenor",
    TextReplace: "Sostituzione testo",
    ThemeAttributes: "Attributi tema",
    TimeBarAllActivities: "Barra tempo per tutte le attività",
    Translate: "Traduci",
    TypingIndicator: "Indicatore digitazione",
    TypingTweaks: "Miglioramenti digitazione",

    Unindent: "Rimuovi rientro",
    UnlockedAvatarZoom: "Zoom avatar sbloccato",
    UnsuppressEmbeds: "Ripristina anteprime incorporate",
    UrbanDictionary: "Urban Dictionary",
    UserMessagesPronouns: "Pronomi nei messaggi utente",
    UserSettingsAPI: "API impostazioni utente",
    UserVoiceShow: "Mostra canale vocale utente",
    USRBG: "USRBG",

    ValidReply: "Risposte valide",
    ValidUser: "Utente valido",
    VcNarrator: "Narratore vocale",
    VencordToolbox: "Strumenti Vencord",
    ViewIcons: "Visualizza icone",
    ViewRaw: "Visualizza contenuto grezzo",
    VoiceChatDoubleClick: "Doppio clic chat vocale",
    VoiceDownload: "Scarica messaggi vocali",
    VoiceMessages: "Messaggi vocali",
    VolumeBooster: "Amplificatore volume",

    WhoReacted: "Chi ha reagito",
    Wikisearch: "Ricerca Wiki",

    XSOverlay: "Overlay XS",

    YoutubeAdblock: "Blocco pubblicità YouTube"
};

export function getItalianPluginName(name: string): string {
    return italianPluginNames[name] ?? name;
}